language: node_js

node_js: stable

sudo: required

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - npm install hexo-cli -g
    - chmod +x ./publish-to-gh-pages.sh

install:
    - npm install

script:
    - hexo clean
    - hexo g

after_script:
    - ./publish-to-gh-pages.sh

branches:
    only:
        - hexo

env:
    global:
        - GH_REF: github.com/Leafney/Leafney.github.io.git