language: node_js # 语言

node_js: stable # 设置相应版本

install:
    - npm install # 安装hexo及插件

script:
    - hexo clean # 清除
    - hexo g # 生成

after_script:
    - cd ./public
    - git init
    - git config user.name "Leafney"
    - git config user.email "babycoolzx@126.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master #GH_TOKEN是在Travis中配置token的名称

branches:
    only:
        - hexo # #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置

env:
    global:
        - GH_REF: https://github.com/Leafney/Leafney.github.io.git #设置GH_REF，注意更改成自己的仓库地址